### ISSUE TITLE
errors in getting MLM-zero

### ISSUE THREAD

**Issue by wiqijan2002** [heraclex12/NLP2SPARQL#3]
Plz advise what to do in this scenario
![2022-07-06 (2)](https://user-images.githubusercontent.com/38495673/178020551-f5ee7ace-7fc9-4e04-99bb-9f0a089d9b6c.png)

**Comment by heraclex12** [comment]
Hi @wiqijan2002 

You should use full the model name like this `AutoTokenizer.from_pretrained('razent/spbert-mlm-zero')`

**Comment by wiqijan2002** [comment]
Thanks, one more thing, I got GPU installed and also Cuda 11.0 but i think its not picked by the program
